/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#dce2f3",
        "surface-container-low": "#f0f3ff",
        "tertiary": "#010100",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#ebf1ff",
        "on-tertiary-fixed-variant": "#474744",
        "primary-container": "#1c1c1c",
        "on-secondary-fixed": "#241a00",
        "inverse-primary": "#c8c6c5",
        "surface-container-highest": "#dce2f3",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "secondary-fixed": "#ffe08f",
        "inverse-surface": "#2a313d",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#1b1b1b",
        "background": "#f9f9ff",
        "secondary": "#755b00",
        "primary-fixed": "#e5e2e1",
        "tertiary-fixed": "#e4e2de",
        "on-tertiary-container": "#858481",
        "on-primary-fixed-variant": "#474746",
        "on-secondary-fixed-variant": "#584400",
        "secondary-fixed-dim": "#e6c364",
        "surface-dim": "#d3daea",
        "on-surface-variant": "#444748",
        "on-background": "#151c27",
        "on-secondary-container": "#785d00",
        "surface-tint": "#5f5e5e",
        "primary-fixed-dim": "#c8c6c5",
        "surface-container": "#e7eefe",
        "outline-variant": "#c4c7c7",
        "surface": "#f9f9ff",
        "tertiary-container": "#1b1c1a",
        "on-secondary": "#ffffff",
        "outline": "#747878",
        "surface-bright": "#f9f9ff",
        "secondary-container": "#fed977",
        "primary": "#010101",
        "on-tertiary": "#ffffff",
        "on-surface": "#151c27",
        "surface-container-high": "#e2e8f8",
        "error": "#ba1a1a",
        "on-primary-container": "#858484",
        "on-tertiary-fixed": "#1b1c1a",
        "tertiary-fixed-dim": "#c8c6c3",
        "on-error": "#ffffff",
        charcoal: "#1C1C1C",
        gold: "#C9A84C",
        ivory: "#F9F8F3",
        slate: "#708090",
      },
      fontFamily: {
        heading: ["Noto Serif", "serif"],
        headline: ["Noto Serif", "serif"],
        body: ["Inter", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
      spacing: {
        'margin-safe': '5vw',
        'gutter': '1.5rem',
        'xl': '4rem',
      },
    },
  },
  plugins: [],
};
